/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myswingstore;

/**
 *
 * @author Lance
 */
public class TransactionFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
    public TransactionFrame() {
        initComponents();
        
        productDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(StoreDatabase.productList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productDropdown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        qtyInput = new javax.swing.JTextField();
        buyButton = new javax.swing.JButton();
        logsButton = new javax.swing.JButton();
        invButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Store Checkout System");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Select Product");

        productDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productDropdown.addActionListener(this::productDropdownActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter Quantity:");

        buyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buyButton.setText("Complete Transaction");
        buyButton.addActionListener(this::buyButtonActionPerformed);

        logsButton.setBackground(new java.awt.Color(153, 153, 153));
        logsButton.setText("View Logs");
        logsButton.addActionListener(this::logsButtonActionPerformed);

        invButton.setBackground(new java.awt.Color(153, 153, 153));
        invButton.setText("View Inventory");
        invButton.addActionListener(this::invButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(invButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtyInput)
                                .addComponent(productDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qtyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logsButton)
                    .addComponent(invButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        try {
    // 1. Get what the user selected and typed
    int selectedIndex = productDropdown.getSelectedIndex(); // 0 for Rice, 1 for Sugar, etc.
    String inputText = qtyInput.getText();
    int qty = Integer.parseInt(inputText); // Converts the typed text into an integer
    
    // 2. Error Handling: Prevent negative or zero quantities
    if (qty <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid quantity greater than 0.");
        return; // Stops the code from continuing
    }
    
    // 3. Error Handling: Prevent buying more than what is in stock
    if (qty > StoreDatabase.stockAvailable[selectedIndex]) {
        javax.swing.JOptionPane.showMessageDialog(this, "Insufficient stock! Only " 
                + StoreDatabase.stockAvailable[selectedIndex] + " left.");
        return; 
    }
    
    // 4. Computations: Calculate the total cost
    double totalCost = qty * StoreDatabase.priceList[selectedIndex];
    
    // 5. Array Updates: Deduct from inventory
    StoreDatabase.stockAvailable[selectedIndex] -= qty;
    
    // 6. Array Updates: Save to transaction history logs
    // We use the 'transactionCount' as the index so we know exactly which slot to fill in the array
    StoreDatabase.historyItems[StoreDatabase.transactionCount] = StoreDatabase.productList[selectedIndex];
    StoreDatabase.historyQuantities[StoreDatabase.transactionCount] = qty;
    StoreDatabase.historyTotals[StoreDatabase.transactionCount] = totalCost;
    
    // Move the counter up by 1 so the next purchase goes into the next slot
    StoreDatabase.transactionCount++; 
    
    // 7. Success Message
    javax.swing.JOptionPane.showMessageDialog(this, "Purchase Successful!\nTotal Cost: ₱" + totalCost);
    
    // 8. Clear the text field for the next customer
    qtyInput.setText("");
    
} catch (NumberFormatException e) {
    // Error Handling: If the user types letters like "ABC" instead of a number
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Quantity must be a whole number.");
}
    }//GEN-LAST:event_buyButtonActionPerformed

    private void logsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButtonActionPerformed
        new LogsFrame().setVisible(true);
    }//GEN-LAST:event_logsButtonActionPerformed

    private void invButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invButtonActionPerformed
        new InventoryFrame().setVisible(true);
    }//GEN-LAST:event_invButtonActionPerformed

    private void productDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productDropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton invButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logsButton;
    private javax.swing.JComboBox<String> productDropdown;
    private javax.swing.JTextField qtyInput;
    // End of variables declaration//GEN-END:variables
}
